"""init

Revision ID: 2fe41cb9a8db
Revises: 
Create Date: 2026-06-02 15:25:26.006764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe41cb9a8db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panthera_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'partial', 'failed', name='sync_status'), nullable=False),
    sa.Column('ordini_importati', sa.Integer(), nullable=True),
    sa.Column('ordini_aggiornati', sa.Integer(), nullable=True),
    sa.Column('errori', sa.Integer(), nullable=True),
    sa.Column('messaggio', sa.Text(), nullable=True),
    sa.Column('payload_raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'tecnico', 'magazzino', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plate_number', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('panthera_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panthera_id', sa.String(length=64), nullable=False),
    sa.Column('panthera_code', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=256), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('order_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='order_status'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('van_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['van_id'], ['vans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panthera_id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('panthera_order_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending_ocr', 'ocr_done', 'validated', 'rejected', name='receipt_status'), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_date', sa.Date(), nullable=True),
    sa.Column('ocr_supplier', sa.String(length=256), nullable=True),
    sa.Column('ocr_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['panthera_order_id'], ['panthera_orders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panthera_order_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_user_id', sa.Integer(), nullable=False),
    sa.Column('van_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'rda_requested', name='service_doc_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['panthera_order_id'], ['panthera_orders.id'], ),
    sa.ForeignKeyConstraint(['tecnico_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['van_id'], ['vans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reintegration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_document_id', sa.Integer(), nullable=False),
    sa.Column('van_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_preparation', 'ready', 'delivered', name='rda_status'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_document_id'], ['service_documents.id'], ),
    sa.ForeignKeyConstraint(['van_id'], ['vans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_document_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_document_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_document_id'], ['service_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reintegration_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reintegration_request_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_missing', sa.Integer(), nullable=False),
    sa.Column('expected_arrival', sa.DateTime(), nullable=True),
    sa.Column('warehouse_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reintegration_request_id'], ['reintegration_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reintegration_request_items')
    op.drop_table('service_document_materials')
    op.drop_table('reintegration_requests')
    op.drop_table('service_documents')
    op.drop_table('receipts')
    op.drop_table('panthera_orders')
    op.drop_table('vans')
    op.drop_table('users')
    op.drop_table('panthera_sync_logs')
    # ### end Alembic commands ###
