"""add commessa to service_documents

Revision ID: 4fbd9900bfbf
Revises: 2fe41cb9a8db
Create Date: 2026-06-03 21:18:26.910786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbd9900bfbf'
down_revision = '2fe41cb9a8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commessa', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_documents_commessa'), ['commessa'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_documents_commessa'))
        batch_op.drop_column('commessa')

    # ### end Alembic commands ###
