"""add rda_panthera fields to reintegration_requests

Revision ID: bd5f4ac3e925
Revises: 4fbd9900bfbf
Create Date: 2026-06-03 21:23:22.636494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5f4ac3e925'
down_revision = '4fbd9900bfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reintegration_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expected_arrival', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rda_panthera_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rda_panthera_code', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reintegration_requests', schema=None) as batch_op:
        batch_op.drop_column('rda_panthera_code')
        batch_op.drop_column('rda_panthera_date')
        batch_op.drop_column('expected_arrival')
        batch_op.drop_column('warehouse_notes')

    # ### end Alembic commands ###
